# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_file', '0010_removed_null_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='link_block',
            field=models.BooleanField(default=False, help_text='Extends the button to the width of its container.', verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='file',
            name='link_context',
            field=models.CharField(blank=True, choices=[('link', 'Link'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], max_length=255, verbose_name='Context'),
        ),
        migrations.AddField(
            model_name='file',
            name='link_outline',
            field=models.BooleanField(default=False, help_text='Removes the button background, keeping only a coloured border.', verbose_name='No background'),
        ),
        migrations.AddField(
            model_name='file',
            name='link_size',
            field=models.CharField(blank=True, choices=[('btn-sm', 'Small'), ('', 'Medium'), ('btn-lg', 'Large')], max_length=255, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='file',
            name='link_type',
            field=models.CharField(choices=[('link', 'Link'), ('btn', 'Button')], default='btn', help_text='Adds either the .btn-* or .text-* classes.', max_length=255, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, help_text='Overrides the default file display name with the given value.', max_length=255, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='link_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link title attrubute'),
        ),
    ]
