# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_file', '0012_auto_20190222_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='show_terms',
            field=models.BooleanField(default=False, verbose_name='Show terms'),
        ),
    ]
